version: 0.2

phases:
  install:
    runtime-versions:
       nodejs: 16    
  pre_build:
    commands:
      - node --version
      - docker --version
      - echo Logging in to Amazon ECR.....
      - aws --version
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 555527584255.dkr.ecr.us-east-1.amazonaws.com)
      - REPOSITORY_URI=555527584255.dkr.ecr.us-east-1.amazonaws.com/nginx-docker-delivery
      - IMAGE_TAG=nginx-docker-delivery | cut -c latest)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"nginx-docker-delivery","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG:latest> imagedefinitions.json
artifacts:
    files: imagedefinitions.json