version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - docker --version
      - node --version
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
  build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 555527584255.dkr.ecr.us-east-1.amazonaws.com
      - docker build -t nginx-docker-delivery .
      - docker tag nginx-docker-delivery:latest 555527584255.dkr.ecr.us-east-1.amazonaws.com/nginx-docker-delivery:latest
  post_build:
    commands:
      - docker push 555527584255.dkr.ecr.us-east-1.amazonaws.com/nginx-docker-delivery:latest
artifacts:
    files: imagedefinitions.json