version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18       
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 555527584255.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t nginx-docker-delivery .
      - docker tag nginx-docker-delivery:latest 555527584255.dkr.ecr.us-east-1.amazonaws.com/nginx-docker-delivery:latest
      - docker push 555527584255.dkr.ecr.us-east-1.amazonaws.com/nginx-docker-delivery:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - echo Writing image definitions file...
      - printf '[{"name":"nginx-docker-delivery","imageUri":"%s"}]' 555527584255.dkr.ecr.us-east-1.amazonaws.com/nginx-docker-delivery:nginx-docker-delivery > imagedefinitions.json
artifacts:
    files: imagedefinitions.json